consumes:
- application/json
produces:
- application/json
schemes:
- http
swagger: "2.0"
info:
  title: http_probe
  version: 0.0.1
paths:
  /probe:
    post:
      tags:
        - probe
      operationId: createProbe
      parameters:
        - name: body
          required: true
          in: body
          schema:
            $ref: "#/definitions/Probe"
      responses:
        201:
          description: created
          schema:
            $ref: "#/definitions/Probe"
definitions:
  Probe:
    properties:
      name:
        type: string
      address:
        type: string
